services:
  - type: web
    name: nids-v2
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --workers 1 --threads 2 --timeout 600 --bind 0.0.0.0:$PORT
    envVars:
      - key: UPLOAD_FOLDER
        value: /tmp/nids_uploads
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: MPLBACKEND
        value: Agg
