services:
  - type: web
    name: nids-v2
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python start.py
    envVars:
      - key: UPLOAD_FOLDER
        value: /tmp/nids_uploads
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: MPLBACKEND
        value: Agg
